### ISSUE TITLE
[BUG] ResizeObserver bug with Picker component 

### ISSUE THREAD

**Issue by bstopyra** [livechat/design-system#1033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After upgrading the @livechat/design-system-react-components package from 1.9.0 to 1.16.7 in the Developer Console, we observed a ResizeObserver bug with a Picker component (the error is displayed only in local env).

We can fix it locally, but I know for a fact that the MP repo had the same issue (they weren't shown the error on the front cause of the older version of React), so I think addressing this issue at hand should be the solution.

### Steps To Reproduce

1. Clone the `developer-console` repo and go to `feature/DS-bug`
2. Make sure you use node version 16.13.2
3. Install all dependencies and run the repo locally
4. Create an app, add an authorization building block go inside it, and try to change the `Client type` (this is just an example, every Picker inside the repo has this issue)

### Expected Behavior

No error screen 

### Screenshots

![image](https://github.com/livechat/design-system/assets/73473782/cd318d06-596b-454f-8024-e5cbbc4208c3)
![image](https://github.com/livechat/design-system/assets/73473782/1624d768-5003-4830-a52b-a6aab3f418db)

### Design system package(s) version

  - @livechat/design-system-react-components@1.16.7

### Environment

Localhost

**Comment by RakowskiPrzemyslaw** [comment]
how's progress on this one? also having issue with that

**Comment by marcinsawicki** [comment]
The `Picker` component uses `Virtuoso`, which uses the `ResizeObserver` interface in its logic, and the problem comes from there.
The official `Virtuoso` site shows that this is known issue with the Webpack dev server and the `ResizeObserver` API used by Virtuoso. [link](https://virtuoso.dev/troubleshooting/#webpack-dev-server-shows-an-error-uncaught-error-resizeobserver-loop-completed-with-undelivered-notifications)
The solution is to silence this error in the local environment.
