### ISSUE TITLE
[BUG] <rangedatepicker-crash-error>

### ISSUE THREAD

**Issue by dgarbaczli** [livechat/design-system#1092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Component <RangeDatePicker [...]/> crashes whole react application.
`Uncaught TypeError: c is not a function`

### Steps To Reproduce

Just montage component from example 
`<RangeDatePicker
  toMonth={new Date('06/20/2023')}
  initialFromDate={new Date('2023-07-01')}
  initialToDate={new Date('2023-07-10')}
/>`

### Expected Behavior

Should works.

### Screenshots

<img width="825" alt="image" src="https://github.com/livechat/design-system/assets/140385379/f93c58a0-cd75-4e98-9ec5-1cf73d4dc1fc">

### Design system package(s) version

    "@livechat/design-system-react-components": "^1.21.1",

### Environment

```markdown
React 18.2.0, newest design system library, all browsers.
```

**Comment by marcinsawicki** [comment]
Hi.
I looked into this issue and noticed that there is an incorrect code snippet in our documentation regarding the example implementation of this component. `RangeDatePicker` requires the use of `DatePicker` as children in order to function.
We have made a change in the documentation to include the full implementation.
