### ISSUE TITLE
[Checkbox] - Improve implementation details with a11y features

### ISSUE THREAD

**Issue by marcinsawicki** [livechat/design-system#510]
Improve implementation details with `a11y` features like `role=checkbox` and `aria-selected="true"`, etc.
It will also improve the possibility to write the tests for this component.

**Comment by ashbork** [comment]
There's another, minor issue which I can fix separately and it doesn't break anything; the div is actually selectable which causes some issues in our app. We have a custom implementation for Shift-clicking checkboxes to select all items between two specific boxes; this breaks with the DS component because the items are selectable and default behavior kicks in. This can be fixed with `user-select:none` on the parent and `user-select:text` on inner elements that should be selectable.

**Comment by vladko-uxds** [comment]
Please use another color token for check icon
--content-invert-primary

**Comment by ashbork** [comment]
Done, thanks @vladko-uxds
